### ISSUE TITLE
npm install fails on OSX, make target 'sodium' not found?

### ISSUE THREAD

**Issue by carlos8f** [paixaop/node-sodium#74] opened 2016-05-07 19:49 UTC
Hello,

I'm having trouble installing sodium on node 4.x, npm 3.x, OSX El Capitan.

when I `npm install sodium` this happens: https://gist.github.com/carlos8f/3ae81319be53ee87fc9daa3659e3774a

However, I can clone the repo and run `make sodium` without error. The problem is when npm tries to compile it. Tried npm 2.x and same error.

Thanks,
Carlos

**Comment by juanpin** [comment] 2016-05-12 19:40
I have the same problem... any ideas?

**Comment by juanpin** [comment] 2016-05-13 19:08
I checked out the code and before running make sodium, you have to run npm install, which is a strange requirement , because it runs $(BINDIR)/node-gyp rebuild from node_modules. I believe there is an error in the instructions to verify that the library builds, it should be verified by just running make libsodium. 

Anyway, I cleared the node-modules and added lib sodium to my dependencies in package.json, ran npm install on my project and then it worked fine.

**Comment by NHQ** [comment] 2016-05-24 18:31
I get same error on ubuntu 14.x, node 5.3.0, npm@3.9.2.

**Comment by m1el** [comment] 2016-05-30 12:30
The latest version (1.1.1) of sodium package on npm is missing the `Makefile`, so it cannot install the node module.

how to check:

    wget https://registry.npmjs.org/sodium/-/sodium-1.1.1.tgz -qO sodium-1.1.1-npm.tgz
    tar ztf sodium-1.1.1-npm.tgz | grep package/Makefile

It happens probably due to this bug: https://github.com/npm/npm/issues/5082

Workaround: add `files` section to `package.json` and explicitly list files to include.

**Comment by NHQ** [comment] 2016-05-30 20:18
@m1el  thanks, can you be more explicit about the workaround please?

**Comment by m1el** [comment] 2016-05-30 20:28
@NHQ you can inspect the changes in [#76](https://github.com/paixaop/node-sodium/pull/76/files).

**Comment by cjb** [comment] 2016-06-03 18:52
Anyone else looking for a workaround: `npm i sodium@~1.0.0` grabs the latest available version before the breaking changes that happened as part of 1.1.0.

**Comment by paixaop** [comment] 2016-06-04 02:06
Guys, sorry for the inconvenience of this latest version. I'm working to fix this. Like m1el the make file is missing form the package I will add it back

**Comment by paixaop** [comment] 2016-06-04 03:41
The issue is in the latest version of libsodium. They added some files needed by `autogen.sh` to their `.gitignore` file and `npm pack` was not including them in the package. Opened an issue with libsodium https://github.com/jedisct1/libsodium/issues/403, but in the mean time I deleted their `.gitignore` from `deps/libsodium` and `npm pack` includes all the files that are needed.

Pushed version 1.1.5 to npmjs which installs correctly in my Mac. Please try it out and let me know.

**Comment by paixaop** [comment] 2016-06-13 02:24
no further comments so closing. thanks for identifying this issue

**Closed by paixaop** 2016-06-13 02:24 UTC
